FROM python:3.8
#RUN apt-get update && apt-get install curl -y
#RUN curl -L https://github.com/dolthub/dolt/releases/download/v0.28.5/install.sh | bash
RUN curl -L https://github.com/dolthub/dolt/releases/download/v0.37.1/install.sh | bash